"""initial schema

Revision ID: 42baf32fc9f1
Revises: 
Create Date: 2026-09-27 00:00:12.902423
"""
import sqlalchemy as sa
from alembic import op

revision = '42baf32fc9f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('sources_total', sa.Integer(), nullable=False),
    sa.Column('sources_ok', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('postings_seen', sa.Integer(), nullable=False),
    sa.Column('postings_new', sa.Integer(), nullable=False),
    sa.Column('postings_closed', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('ats', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('discovered_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('first_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=40), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_count', sa.Integer(), nullable=True),
    sa.Column('last_nl_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ats', 'slug', name='uq_source_ats_slug')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_ats'), ['ats'], unique=False)

    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location_raw', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('is_tech', sa.Boolean(), nullable=True),
    sa.Column('tech_score', sa.Double(), nullable=True),
    sa.Column('extraction', sa.JSON(), nullable=True),
    sa.Column('extractor_version', sa.String(length=60), nullable=True),
    sa.Column('extracted_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_posting_source_external')
    )
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.create_index('ix_posting_dedup', ['dedup_key'], unique=False)
        batch_op.create_index('ix_posting_first_seen', ['first_seen'], unique=False)
        batch_op.create_index('ix_posting_open', ['closed_at', 'is_tech'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postings_source_id'))
        batch_op.drop_index(batch_op.f('ix_postings_country'))
        batch_op.drop_index(batch_op.f('ix_postings_company'))
        batch_op.drop_index(batch_op.f('ix_postings_city'))
        batch_op.drop_index('ix_posting_open')
        batch_op.drop_index('ix_posting_first_seen')
        batch_op.drop_index('ix_posting_dedup')

    op.drop_table('postings')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_ats'))

    op.drop_table('sources')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
