"""meta table

Revision ID: 54fa914ff2c5
Revises: 5bfd72b8943a
Create Date: 2026-09-27 11:41:16.209370
"""
import sqlalchemy as sa
from alembic import op

revision = '54fa914ff2c5'
down_revision = '5bfd72b8943a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    # ### end Alembic commands ###
