"""link check columns

Revision ID: 5bfd72b8943a
Revises: e1c5cc622c95
Create Date: 2026-09-27 11:01:37.787102
"""
import sqlalchemy as sa
from alembic import op

revision = '5bfd72b8943a'
down_revision = 'e1c5cc622c95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('link_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_column('link_status')
        batch_op.drop_column('link_checked_at')

    # ### end Alembic commands ###
