"""source kind

Revision ID: e1c5cc622c95
Revises: 42baf32fc9f1
Create Date: 2026-09-27 00:19:42.100557
"""
import sqlalchemy as sa
from alembic import op

revision = 'e1c5cc622c95'
down_revision = '42baf32fc9f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
