apiVersion: v1
kind: Service
metadata:
  name: {{ include "radar.fullname" . }}-api
  labels: {{- include "radar.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: {{ include "radar.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar.fullname" . }}-api
  labels: {{- include "radar.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  strategy: {{- toYaml .Values.api.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radar.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: /metrics
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          env: {{- include "radar.env" . | nindent 12 }}
          readinessProbe:
            httpGet: {path: /readyz, port: http}
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 20
            failureThreshold: 3
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
{{- if .Values.api.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "radar.fullname" . }}-api
  labels: {{- include "radar.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "radar.fullname" . }}-api
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
