{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radar.fullname" . }}-db
  labels: {{- include "radar.labels" . | nindent 4 }}
type: Opaque
stringData:
  RADAR_DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
{{- if and (not .Values.admin.existingSecret) .Values.admin.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radar.fullname" . }}-admin
  labels: {{- include "radar.labels" . | nindent 4 }}
type: Opaque
stringData:
  RADAR_ADMIN_TOKEN: {{ .Values.admin.token | quote }}
{{- end }}
